### ISSUE TITLE
Proyecto Final_

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/proyecto-final-turbanda#2]
[Practica Final Tópicos Avanzados De Programacion.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-turbanda/files/6801652/Practica.Final.Topicos.Avanzados.De.Programacion.pdf)

**Comment by Anthony4523** [comment]
Calificación: 80 / 80
Calificó Antonio González Hernández

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
